[package]
name = "overpass-turbo"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { version = "*", features = ["derive"] }
serde_json = "*"
#geojson = "*"
#geo-types=  "*"

[features]
simple = []
